### ISSUE TITLE
Detail missing in normal map 

### ISSUE THREAD

**Issue by hrkrx** [jayanam/jbake-tools#14]
I tried this addon with a basic barrel, but details on the lid are not being baked to the normal map.
![image](https://user-images.githubusercontent.com/5176531/145425197-61c4a7a8-e102-4b24-b813-c5338d0e72c5.png)

**Comment by jayanam** [comment]
Hard to say, could you attach the project?

**Comment by hrkrx** [comment]
Thanks for the fast reply! :)
[BarrelBase.zip](https://github.com/jayanam/jbake-tools/files/7687208/BarrelBase.zip)

My setup:
Windows
Blender 3

**Comment by nobody118** [comment]
I opened your project and did some digging - Turns out the faces on the sides of whatever detail is sticking out can't be perfectly straight or the normal map won't have any depth. This seems to just be how it works in Blender, rather than anything specific to this addon.

I found this out by watching this video. You can see it shortly before the 5 minute mark: https://www.youtube.com/watch?v=zwEXUN83LeI

The video is probably worth watching from the beginning because he goes over a great workflow for being able to see what the normal map is going to look like in realtime as you edit the model.

After adjusting those side faces to no longer be perfectly straight, this is what the low poly barrel looks like:
![image](https://user-images.githubusercontent.com/100808080/156462132-f275f4d7-784e-48ab-8eb9-7466ff7bda5d.png)

**Comment by hrkrx** [comment]
@nobody118 thank you very much :)
